name: FetaruteTCAddon
version: '0.0.1-beta'
main: org.fetarute.fetaruteTCAddon.FetaruteTCAddon
api-version: '1.20'
authors: [ Acatine ]
website: www.fetarute.org
depend:
  - BKCommonLib
  - Train_Carts
softdepend:
  - TCCoasters
commands:
  fta:
    description: FetaruteTCAddon 主命令
    usage: /fta <info|help|reload|company|operator|line|route|depot|graph|occupancy|train>
permissions:
  fetarute.admin:
    description: 全局管理员权限
    default: op
    children:
      fetarute.graph: true
      fetarute.graph.build: true
      fetarute.graph.continue: true
      fetarute.graph.status: true
      fetarute.graph.cancel: true
      fetarute.graph.delete: true
      fetarute.graph.info: true
      fetarute.graph.sign: true
      fetarute.graph.query: true
      fetarute.graph.edge: true
      fetarute.depot.spawn: true
      fetarute.occupancy: true
      fetarute.occupancy.debug: true
      fetarute.train.config: true
  fetarute.reload:
    description: 重新加载 FetaruteTCAddon 配置
    default: op
  fetarute.company.create:
    description: 创建公司
    default: true
  fetarute.graph:
    description: 调度图相关命令（/fta graph）
    default: op
  fetarute.graph.build:
    description: 构建并持久化调度图（/fta graph build）
    default: op
  fetarute.graph.continue:
    description: 续跑调度图构建任务（/fta graph continue）
    default: op
  fetarute.graph.status:
    description: 查看调度图构建进度（/fta graph status）
    default: op
  fetarute.graph.cancel:
    description: 取消调度图构建任务（/fta graph cancel）
    default: op
  fetarute.graph.delete:
    description: 删除调度图快照或局部分量（/fta graph delete）
    default: op
  fetarute.graph.info:
    description: 查看调度图摘要与区间距离（/fta graph info）
    default: op
  fetarute.graph.query:
    description: 查询调度图可达性与最短路（/fta graph query/path/component）
    default: op
  fetarute.graph.edge:
    description: 区间运维控制（限速/临时限速/封锁）（/fta graph edge ...）
    default: op
  fetarute.graph.sign:
    description: 快速设置节点牌子内容（/fta graph sign ...）
    default: op
  fetarute.depot.spawn:
    description: 手动触发车库生成列车（/fta depot spawn）
    default: op
  fetarute.occupancy:
    description: 调度占用诊断与清理（/fta occupancy）
    default: op
  fetarute.occupancy.debug:
    description: 调度占用调试命令（/fta occupancy debug）
    default: op
  fetarute.train.config:
    description: 列车加减速/速度配置（/fta train config）
    default: op
