name: FetaruteTCAddon
version: '0.0.1-beta'
main: org.fetarute.fetaruteTCAddon.FetaruteTCAddon
api-version: '1.20'
authors: [ Acatine ]
website: www.fetarute.org
depend:
  - BKCommonLib
  - Train_Carts
commands:
  fta:
    description: FetaruteTCAddon 主命令
    usage: /fta <info|help|reload>
permissions:
  fetarute.reload:
    description: 重新加载 FetaruteTCAddon 配置
    default: op
